document.write('<ul>')
document.write('<li><a href="index.html">Home</a></li>')
document.write('<li><a href="services.html">Services</a></li>')
document.write('<li><a href="capabilities.html">Core Capabilities</a></li>')
document.write('<li><a href="support.html">Support</a></li>')
document.write('<li><a href="employment.html">Employment</a></li>')
document.write('<li><a href="resources.html">Resources</a></li>')
document.write('<li><a href="position.html">Position Statements</a></li>')
document.write('<li><a href="contact.html">Contact</a></li>')
document.write('<li class="last"><a href="about.html">About</a></li>')
document.write('</ul>')