document.write('<h3 class="title">Software Engineering Services</h3>')
document.write('<h4>Use IT</h4>')
document.write('<p>Intelligently adopt srategic open source and open standards within your organisation by aligning your architecural policies with key industry initiatives.</p>')
document.write('<h4>Build IT</h4>')
document.write('<p>Create working solutions that are modular, extensible and reliable through the selective assembly of reusable components, frameworks and building blocks.</p>')
document.write('<h4>Map IT</h4>')
document.write('<p>Reverse engineer your enterprise architecture and applications.</p>')
document.write('<h4>Model IT</h4>')
document.write('<p>Leverage the power of conceptual modelling by utilising domain modelling and rules specification techniques to dramatically streamline development practices.</p>')
document.write('<h4>Work IT</h4>')
document.write('<p>Optimise processes and streamline workflows by enabling automation and maximising human involvement.</p>')
document.write('<h4>Define IT</h4>')
document.write('<p>Establish strong leadership and direction on projects through the clear specification of requirements, functions, feature sets and outcomes.</p>')
